// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaShop.Data;

#nullable disable

namespace PizzaShop.Migrations
{
    [DbContext(typeof(PizzaShopDbContext))]
    [Migration("20260814052241_InsertPizzas")]
    partial class InsertPizzas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("PizzaShop.Domain.Model.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pizza with tomatoes, mozzarella, basil, extra virgin olive oil",
                            Name = "Margherita",
                            Price = 15.50m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pizza with pepperoni and mozzarella",
                            Name = "Pepperoni",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pizza with Mozzarella, Gorgonzola, Fontina, Parmesan",
                            Name = "Four Cheese",
                            Price = 16.82m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
